enum DB {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_SSL_REQUIRED = 'DB_SSL_REQUIRED',
  DB_MASTER_HOST = 'DB_MASTER_HOST',
  DB_SLAVE_HOST = 'DB_SLAVE_HOST',
  TIMEZONE = 'TIMEZONE',
  SCHEMA_NAME = 'SCHEMA_NAME',
}

enum REDIS {
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_QUEUE_DATABASE = 'REDIS_QUEUE_DATABASE',
  REDIS_CACHE_DATABASE = 'REDIS_CACHE_DATABASE',
  REDIS_SSL_REQUIRED = 'REDIS_SSL_REQUIRED',
}

enum STRIPE {
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',
}

enum MOMO {
  MOMO_PARTNER_CODE = 'MOMO_PARTNER_CODE',
  MOMO_ACCESS_KEY = 'MOMO_ACCESS_KEY',
  MOMO_SECRET_KEY = 'MOMO_SECRET_KEY',
  MOMO_ENDPOINT = 'MOMO_ENDPOINT',
  MOMO_IPN_URL = 'MOMO_IPN_URL',
  MOMO_REDIRECT_URL = 'MOMO_REDIRECT_URL',
  MOMO_STORE_ID = 'MOMO_STORE_ID',
}

export const ConfigServiceKeys = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  CLIENT_URL: 'CLIENT_URL',
  GOOGLE_GET_USER_INFO_URL: 'GOOGLE_GET_USER_INFO_URL',
  ...DB,
  ...REDIS,
  ...STRIPE,
  ...MOMO,
} as const;

export type ConfigServiceType = typeof ConfigServiceKeys;
