export enum AchievementCode {
  // Group 1a — Diligent (login & first-time slots & island)
  FIRST_FOOTPRINT = 'FIRST_FOOTPRINT',
  WAVE_INITIATOR_3D = 'WAVE_INITIATOR_3D',
  WAVE_RAISER_7D = 'WAVE_RAISER_7D',
  WAVE_CHASER_14D = 'WAVE_CHASER_14D',
  WAVE_BREAKER_21D = 'WAVE_BREAKER_21D',
  WAVE_SHAPER_30D = 'WAVE_SHAPER_30D',
  WAVE_SPIRIT_60D_TOTAL = 'WAVE_SPIRIT_60D_TOTAL',

  MOON_CHASER_FIRST_22_24 = 'MOON_CHASER_FIRST_22_24',
  SUN_CHASER_FIRST_5_7 = 'SUN_CHASER_FIRST_5_7',
  HEAT_SEEKER_FIRST_12_14 = 'HEAT_SEEKER_FIRST_12_14',
  DUSK_DREAMER_FIRST_16_17 = 'DUSK_DREAMER_FIRST_16_17',
  WEEKEND_VOYAGE_FIRST = 'WEEKEND_VOYAGE_FIRST',

  // Group 1b — Neglected Failures (no reward but tracked)
  CURIOUS_SAILOR_NO_LESSON_5M_AFTER_FIRST_LOGIN = 'CURIOUS_SAILOR_NO_LESSON_5M_AFTER_FIRST_LOGIN',
  CHILL_SAILOR_NO_CATEGORY_7D_AFTER_FIRST_LOGIN = 'CHILL_SAILOR_NO_CATEGORY_7D_AFTER_FIRST_LOGIN',

  // Group 2 — Intelligence (accuracy & hard)
  CLEVER_START_10_CORRECT = 'CLEVER_START_10_CORRECT',
  WISE_COMPASS_50_CORRECT = 'WISE_COMPASS_50_CORRECT',
  BULLSEYE_NAVIGATOR_150_CORRECT = 'BULLSEYE_NAVIGATOR_150_CORRECT',
  SAGE_OF_THE_SEAS_500_CORRECT = 'SAGE_OF_THE_SEAS_500_CORRECT',
  IRON_FIST_10_HARD_CORRECT = 'IRON_FIST_10_HARD_CORRECT',
  IRON_WILL_50_HARD_CORRECT = 'IRON_WILL_50_HARD_CORRECT',
  IRON_MIND_100_HARD_CORRECT = 'IRON_MIND_100_HARD_CORRECT',

  // Group 3 — Subject/Category completion count
  CABIN_BOY_1_CATEGORY = 'CABIN_BOY_1_CATEGORY',
  DECKHAND_5_CATEGORIES = 'DECKHAND_5_CATEGORIES',
  NAVIGATOR_10_CATEGORIES = 'NAVIGATOR_10_CATEGORIES',
  FIRST_MATE_50_CATEGORIES = 'FIRST_MATE_50_CATEGORIES',
  CAPTAIN_100_CATEGORIES = 'CAPTAIN_100_CATEGORIES',
}


